---
- name: Warn users if the server's Linux distribution is not Debian 8
  pause: prompt="Debian 8 is the only fully tested distribution; the setup will probably fail. Press Enter if you still want to continue."
  when: ansible_distribution != "Debian" or ansible_distribution_major_version != "8"

# Set default variables
- include: set-default-variables.yml

- name: Ensure the APT cache is up to date
  apt: update_cache=yes
       cache_valid_time=3600

- name: Install Streisand common packages
  apt: name={{ item }}
  with_items: streisand_common_packages

- name: Copy the HTML header and footer templates that are used during documentation generation
  copy: src={{ item.src }}
        dest={{ item.dest }}
  with_items:
    - { src: "header.html", dest: "{{ streisand_header_template }}" }
    - { src: "footer.html", dest: "{{ streisand_footer_template }}" }
