---
tor_bridge_nickname_file: "/etc/tor/bridge_nickname"
tor_obfs_transports:
  - obfs3

tor_standard_connection_details: "{{ streisand_ipv4_address }}:{{ tor_orport }}"
tor_obfs3_connection_details:    "{{ streisand_ipv4_address }}:{{ tor_obfs3_port }}"

tor_obfs3_bridge_line: "bridge://obfs3 {{ tor_obfs3_connection_details }} {{ tor_fingerprint.stdout }}"

tor_hidden_service_directory: "/var/lib/tor/hidden_service/"
tor_hidden_service_url: "http://{{ tor_hidden_service_hostname.stdout }}"

tor_gateway_location: "{{ streisand_gateway_location }}/tor"

tor_markdown_instructions: "{{ tor_gateway_location }}/index.md"
tor_html_instructions: "{{ tor_gateway_location }}/index.html"

tor_obfs3_qr_code: "{{ tor_gateway_location }}/tor-obfs3-qr-code.png"
